services:
    mysql-db:
      image: mysql:8.2
      ports:
          - "3306:3306"
      volumes:
          - mysql_data:/var/lib/mysql
      env_file:
          - src/config/.env
      networks:
          - cnam
      healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
        interval: 10s
        timeout: 5s
        retries: 5

    minio:
      image: minio/minio:latest
      ports:
          - "9000:9000"
          - "9001:9001"
      volumes:
          - minio_data:/data
      entrypoint: ["minio", "server", "--console-address", "0.0.0.0:9001", "/data"]
      networks:
        - cnam

    mlflow:
      image: mlflow-local-server:1.0
      build:
        dockerfile: docker/Dockerfile
      ports:
        - "5000:5000"
      env_file:
        - src/config/.env
      networks:
        - cnam
      depends_on:
        - mysql-db

volumes:
  minio_data:
  mysql_data:

networks:
  cnam: