services:
  mysql-db:
    image: mysql:8.2
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - src/config/.env
    networks:
      - cnam

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    entrypoint: ["minio", "server", "--console-address", "0.0.0.0:9001", "/data"]
    networks:
      - cnam

  mlflow:
    image: mlflow-local-server:1.0
    build:
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5000"
    env_file:
      - src/config/.env
    networks:
      - cnam
    depends_on:
      - mysql-db

volumes:
  mysql-data:
  minio-data:

networks:
  cnam: